# New Travis CI config with platformio integration

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=arduino/SMS

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run
