# New Travis CI config with platformio integration

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - cd arduino/SMS
    - platformio run
    
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
