version: '2'

networks:
  ardu-tracker-net:
    driver: bridge

services:
  webapp:
    build: ./webapp
    container_name: sms_webapp
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "8080:80"
      - "4430:443"
    volumes: 
      - ./webapp:/var/www/html/